/**
 * Brand copy. Calm, minimalist, confident. UK English. No exclamation marks.
 * Members, never customers. "Your Club", "drop", "arrival", "curated".
 */
export const COPY = {
  brand: 'Cannibisters',
  brandLong: 'Cannibisters Herbal Apothecary',
  tagline: 'Members-only cannabis club and herbal apothecary, Sea Point.',
  address: '65 Regent Rd, Sea Point',
  hours: 'Open daily, 09:00 to 23:30',
  phone: '+27 87 537 8000',
  whatsapp: '+27 66 344 3012',
  whatsappUrl: 'https://wa.me/27663443012',
  instagram: 'https://www.instagram.com/cannibisterscapetown',
  website: 'https://cannibisters.com',
  registerUrl: 'https://cannibisters.com/account/register',
  freeDeliveryThreshold: 700,
  signIn: {
    eyebrow: 'Members',
    title: 'Welcome back.',
    lede: 'Sign in with the same details you use on cannibisters.com. Nothing new to set up.',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    forgot: 'Forgot your password?',
    notMember: 'Not a member yet?',
    apply: 'Apply to join.',
    applyHint: 'Applications take a couple of minutes and are reviewed by our team, usually within 24 hours.',
  },
  home: {
    greeting: (name: string) => `Evening, ${name}.`,
    greetingDay: (name: string) => `Good day, ${name}.`,
    greetingNight: (name: string) => `Still up, ${name}.`,
    entryCta: 'Show my entry code',
    specialsTitle: 'App exclusives',
    specialsSub: 'Only here. Only for members who order through the app.',
    newTitle: 'Just landed',
    sotwTitle: 'Flower of the week',
    cannisinoTitle: 'The Cannisino',
    cannisinoSub: 'Predictions, the Claw Machine, Mines and the Wheel. Points in, prizes out.',
    conciergeTitle: 'Canni Concierge',
    conciergeSub: 'A recommendation, a seat, a pre-order. Ask and it is handled.',
    nightOwlTeaser: 'Night Owl returns at midnight. 15% off online orders until 7am.',
  },
  nightOwl: {
    eyebrow: 'After dark · Midnight to 7am',
    title: 'Night Owl.',
    lede: 'The city is asleep. The apothecary is not. Take your time with the menu; the quiet hours are yours.',
    promo: '15% off everything · midnight to 7am',
    cta: 'Shop the night',
    exit: 'Day mode',
    foot: 'Members only · Order tonight, first delivery slot tomorrow',
    rail: 'Popular tonight',
    rail2: 'Just landed',
  },
  entry: {
    title: 'Your entry code',
    lede: 'Show this at the door. It refreshes on its own.',
    brightness: 'Turn your brightness up for the scanner.',
    expired: 'Your membership has lapsed. Add a day pass to come in tonight.',
    none: 'Your application is still with our team. We will let you know the moment you are approved.',
    dayPass: 'Add a R20 day pass',
  },
  loyalty: {
    title: 'Your points',
    earn: (rate: number) => `${rate} points for every R1, multiplied by your tier.`,
    expiry: 'Points are valid for 12 months. Oldest points go first.',
    redeemTitle: 'Redeem',
    redeemSub: '100 points is worth R1 in rewards.',
  },
  moments: {
    title: 'Club moments',
    sub: 'Sessions, strains and the people you shared them with.',
    compose: 'Share a moment',
    pickProduct: 'What are you enjoying?',
    typeAuto: (type: string) => `Marked as ${type} from the product.`,
    guideline: 'Keep it to the Club. No faces without permission, no minors, nothing for sale.',
  },
  cannisino: {
    title: 'Cannisino',
    sub: 'Members-only games lounge. Points, never money.',
    rules: '21+ members only. Free to play. Winnings settle to your points balance once a day.',
    wallet: 'Play wallet',
  },
  concierge: {
    title: 'Canni Concierge',
    sub: 'Your Club, one message away.',
    intro: 'Tell us what you are after. A strain for the evening, a table for four, an order ready when you arrive.',
    whatsapp: 'Continue on WhatsApp',
  },
  membership: {
    dayPass: 'Day pass · 24 hours',
    plans: [
      { plan: '30 days', price: 100 },
      { plan: '3 months', price: 300 },
      { plan: '6 months', price: 550 },
      { plan: '12 months', price: 1000 },
    ],
  },
  signOff: 'The Cannibisters Team',
} as const;
